services:
  app:
    build: .
    ports:
      - "8050:8050"
    env_file:
      - .env
    volumes:
      - .:/srv
    links: 
      - postgres
    command: flask run

  frontend:
    build:
      context: .
      target: css_build
    volumes:
      - .:/srv
    command: yarn install && yarn watch-css

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"